// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoViviendasFelipe.DbContexts;

#nullable disable

namespace ProyectoViviendasFelipe.Migrations
{
    [DbContext(typeof(ViviendaInfoContext))]
    partial class ViviendaInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("ProyectoViviendasFelipe.Entities.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<string>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ViviendaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ViviendaId");

                    b.ToTable("Reservas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaFin = "15-10-2022",
                            FechaInicio = "10-10-2022",
                            NameUsuario = "Juan Gonzalez",
                            ViviendaId = 1
                        },
                        new
                        {
                            Id = 2,
                            FechaFin = "15-10-2022",
                            FechaInicio = "10-10-2022",
                            NameUsuario = "Javi Ruiz",
                            ViviendaId = 2
                        },
                        new
                        {
                            Id = 3,
                            FechaFin = "27-11-2022",
                            FechaInicio = "20-11-2022",
                            NameUsuario = "Juan Gonzalez",
                            ViviendaId = 2
                        },
                        new
                        {
                            Id = 4,
                            FechaFin = "14-11-2022",
                            FechaInicio = "11-11-2022",
                            NameUsuario = "Alberto Muñoz",
                            ViviendaId = 1
                        });
                });

            modelBuilder.Entity("ProyectoViviendasFelipe.Entities.Vivienda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Propietario")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Viviendas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Casa en las afueras muy grande",
                            Direccion = "Málaga, Marbella, Calle Lopez, n20",
                            Name = "Casa de Campo",
                            Propietario = "Luis Gómez"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Piso en el centro de malaga para turistas",
                            Direccion = "Málaga, Málaga, Calle Granada, n30",
                            Name = "Piso en Ciudad",
                            Propietario = "José Pérez"
                        });
                });

            modelBuilder.Entity("ProyectoViviendasFelipe.Entities.Reserva", b =>
                {
                    b.HasOne("ProyectoViviendasFelipe.Entities.Vivienda", "Vivienda")
                        .WithMany("Reservas")
                        .HasForeignKey("ViviendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vivienda");
                });

            modelBuilder.Entity("ProyectoViviendasFelipe.Entities.Vivienda", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
